inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '.*/**/*'
    - 'benchmark/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 3.1.0

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false
